# Reusable workflow for secret scanning
# Usage in calling workflow:
#   jobs:
#     secret-scan:
#       uses: your-org/security-controls/.github/workflows/secret-scanning.yml@main

name: Secret Scanning

on:
  workflow_call:
    inputs:
      scan-path:
        description: 'Path to scan for secrets'
        required: false
        type: string
        default: '.'
    secrets:
      GITLEAKS_LICENSE:
        required: false

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          args: --path=${{ inputs.scan-path }}

  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified
